### ISSUE TITLE
BoundsError when plotting solution to JumpProblem with default solver

### ISSUE THREAD

**Issue by yha** [JuliaDiffEq/DifferentialEquations.jl#408] opened 2019-01-09 20:32 UTC
Reproducing example:
```
using DifferentialEquations
using Plots
prob = JumpProblem(ODEProblem((du,u,p,t)->(du.=-u), [1.0], (0.0, 1.0)), 
                   Direct(), ConstantRateJump((u,p,t)->1.0, int->()))
sol = solve(prob)
plot(sol)
```
yields `BoundsError: attempt to access 7-element Array{Int64,1} at index [8]` at the last line (the exact numbers vary).
When specifying a `Tsit5` solver (`solve(prob, Tsit5())`), there is no error.

**Comment by ChrisRackauckas** [comment] 2019-01-19 07:02
Could be caused by https://github.com/JuliaDiffEq/DiffEqJump.jl/issues/58

**Comment by ChrisRackauckas** [comment] 2019-02-14 04:49
Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/26bffd7e999be05c31741bc340396132e21c3b79

**Closed by ChrisRackauckas** 2019-02-14 04:49 UTC
