### ISSUE TITLE
Pkg.test("DifferentialEquations") fails

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#137] opened 2017-01-31 09:01 UTC
For the last day or so, Pkg.test("DifferentialEquations") fails. It gives some warnings about DelayDiffEq and then some errors that you should be able to reproduce by running Pkg.test().

**Comment by ChrisRackauckas** [comment] 2017-01-31 09:17
I can't reproduce this on master. What's your `Pkg.status()`?

**Comment by finmod** [comment] 2017-01-31 09:43
![capture](https://cloud.githubusercontent.com/assets/12710434/22459722/fbb44476-e7a1-11e6-94df-9622ccf1bc16.JPG)

**Comment by ChrisRackauckas** [comment] 2017-01-31 09:45
Yeah, you have an odd subset of masters there. It should be working on the current release, and I'll be starting another tag session tomorrow (and it works on master, needs probably DiffEqBase + DelayDiffEq masters)

**Comment by ChrisRackauckas** [comment] 2017-02-07 23:24
This should be fixed on the current release.

**Closed by ChrisRackauckas** 2017-02-07 23:24 UTC

**Comment by finmod** [comment] 2017-02-08 08:04
Sorry, I actually solved this by using Pkg.free(“DifferentialEquations”) and reinstall everything.
