### ISSUE TITLE
Monte Carlo threading segfault

### ISSUE THREAD

**Issue by honghuzi** [JuliaDiffEq/DifferentialEquations.jl#190] opened 2017-07-20 02:55 UTC
I just ran the example code copied from http://docs.juliadiffeq.org/v1.10.1/features/monte_carlo.html:
addprocs(4)
```
using DiffEqMonteCarlo, DiffEqBase, DiffEqProblemLibrary, OrdinaryDiffEq
prob = prob_ode_linear
   prob_func = function (prob)
   prob.u0 = rand()*prob.u0
   prob
end
monte_prob = MonteCarloProblem(prob,prob_func=prob_func)
sim = solve(monte_prob,Tsit5(),num_monte=100)

using Plots
plotly()
plot(sim,linealpha=0.4)
```

my julia version is v0.6.0-rc1. I ran the code in REPL. Everything went well before the "solve()" sentence. When the package tried to "solve" the monte problem, the error shows:
```
ERROR: On worker 2:
MethodError: no method matching (::Base.Serializer.__deserialized_types__.##1#2)(::DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64}}, ::Int64)
Closest candidates are:
  #1(::Any) at REPL[4]:2
#2 at C:\Users\cyb\.julia\v0.6\DiffEqMonteCarlo\src\solve.jl:27
#exec_from_cache#191 at .\distributed\workerpool.jl:284
exec_from_cache at .\distributed\workerpool.jl:283
#106 at .\distributed\process_messages.jl:268 [inlined]
run_work_thunk at .\distributed\process_messages.jl:56
macro expansion at .\distributed\process_messages.jl:268 [inlined]
#105 at .\event.jl:73
Stacktrace:
```

**Comment by ChrisRackauckas** [comment] 2017-07-20 03:05
Somehow you found a very old version of the docs. The updated version is here:

http://docs.juliadiffeq.org/latest/features/monte_carlo.html#Example-1:-Solving-an-ODE-With-Different-Initial-Conditions-1

I just ran it on v0.6 and it works. On v0.6.0-rc1 you might need to be using some old old syntax (which you can find by going back a bunch of versions in the docs)? But anyways, I would recommend upgrading because no package will be testing on v0.6.0-rc1 since that's a pre-release of v0.6 which doesn't really exist anymore. I'm not even sure where you'd download rc1 anymore.

**Comment by honghuzi** [comment] 2017-07-20 03:35
Thanks for your very timely reply. I found the new doc now, and the new codes worked fine.

**Comment by honghuzi** [comment] 2017-07-20 04:10
But when I ran my own code, it ran into the same error. My code looks like:
1. main.jl
```
include("equations.jl")
include("parameter.jl")
include("evolution.jl")
addprocs()
using Evolu
@time Evolution()

```
2. equations.jl
```
@everywhere module Equas
using Parameter
export Eq
function Eq(t, u, du)
    r = sqrt(u[1]^2 +u[2]^2)
    ele = GetEleField(t)
    du[1] = u[3]
    du[2] = u[4]
    du[3] = -u[1]*( z + a1*(1.0+a2*r)*exp(-a2*r) + a3*a4*r^2*exp(-a4*r) + a5*(1.0+a6*r)*exp(-a6*r))/(r^3)
    du[4] = -u[2]*( z + a1*(1.0+a2*r)*exp(-a2*r) + a3*a4*r^2*exp(-a4*r) + a5*(1.0+a6*r)*exp(-a6*r))/(r^3) - ele
    du[5] = 0.5*(u[3]^2+u[4]^2) - (z + a1*exp(-a2*r) + a3*r*exp(-a4*r) + a5*exp(-a6*r)) / r
end
end
```
3. parameter.jl
```
@everywhere module Parameter
export ne, E0, A0, T, TT, N_cycle, Ip, omega, z, a1, a2, a3, a4, a5, a6
export GetEleField 
....
end 
```
4. evolution.jl
```
@everywhere module Evolu
using Parameter, Equas, DifferentialEquations
export Evolution
function Evolution()
...
prob = ODEProblem(Eq, u0, (0, TT)) 
    function prob_func(prob, i)
        prob.u0 = [0.0, y[i], px[i], 0.0, 0.0]
        prob.tspan = (ti[i], TT)
        prob
    end
    monte_prob = MonteCarloProblem(prob, prob_func=prob_func)
    sim = solve(monte_prob, Tsit5(), num_monte=500000; save_everystep=false, dense=false)
end
```

The error message are 
```
ERROR: LoadError: On worker 2:
UndefVarError: DiffEqMonteCarlo not defined
deserialize_module at .\serialize.jl:753
handle_deserialize at .\serialize.jl:695
deserialize at .\serialize.jl:634
deserialize_datatype at .\serialize.jl:967
handle_deserialize at .\serialize.jl:674
deserialize at .\serialize.jl:634
handle_deserialize at .\serialize.jl:681
deserialize at .\serialize.jl:634
ntuple at .\tuple.jl:108
handle_deserialize at .\serialize.jl:664
deserialize at .\serialize.jl:634
ntuple at .\tuple.jl:108
handle_deserialize at .\serialize.jl:664
deserialize_msg at .\distributed\messages.jl:98
message_handler_loop at .\distributed\process_messages.jl:161
process_tcp_streams at .\distributed\process_messages.jl:118
#99 at .\event.jl:73
```

Maybe I put addprocs() in the wrong place. Where should put "addprocs()"? I tried put it at the beginning of main.jl, but I got warning 
`replacing module DifferentialEquations`
Besides, when I performed the monte carlo simulation serially in a for loop, I got the warning: 
`WARNING: dt <= dtmin. Aborting. If you would like to force continuation with dt=dtmin, set force_dtmin=true `
Do I have to change the algorithm? or maybe my problem can't be solve within DifferentialEquations.jl?

**Comment by ChrisRackauckas** [comment] 2017-07-20 05:09
>Where should put "addprocs()"? 

You need to do it before the `@everywhere` and imports, otherwise those won't occur on all processes, and thus you're getting that error because some processes never imported the libraries.

>but I got warning

That warning is harmless, though it should've been fixed on Julia v0.6. In the cases I've checked it has, but maybe it's occurring here because of the `@everywhere` on the modules? I have never used so many modules before. I would try it without all of the modules first, and see if the modules are necessary. This may be worth reporting to the julia repo if you track down what's causing it.

>Do I have to change the algorithm? 

Maybe. If the problem is stiff, then you'd get this warning as it drops `dt` to reduce the error. In that case, you'll want to use a solver for stiff equations and not `Tsit5()`. Or if you want, just add `force_dtmin=true`, but then the error estimator can be violated. So it's probably best to find a different algorithm, or check for errors in `Eq`.

>or maybe my problem can't be solve within DifferentialEquations.jl?

Well DifferentialEquations.jl wraps the other differential equations methods, so either one of the methods work or really nothing will. You can just run the gambit: install ODEInterfaceDiffEq.jl and LSODA.jl, and then try out:

```julia
sim = solve(monte_prob, Tsit5(), num_monte=500000; save_everystep=false, dense=false)
sim = solve(monte_prob, Rosenbrock23(), num_monte=500000; save_everystep=false, dense=false)
sim = solve(monte_prob, dopri5(), num_monte=500000; save_everystep=false, dense=false)
sim = solve(monte_prob, radau(), num_monte=500000; save_everystep=false, dense=false)
sim = solve(monte_prob, CVODE_BDF(), num_monte=500000; save_everystep=false, dense=false)
sim = solve(monte_prob, LSODA(), num_monte=500000; save_everystep=false, dense=false)
```

That'll run through most of the well-known algorithms (`LSODA`, `CVODE_BDF`, `dopri5`, and `radau` are just wrappers to the C and Fortran algorithms) and the native Julia ones, some stiff solvers and some non-stiff. If none of those work, then you can be very very sure it's the problem definition (equation or initial condition) and not the solvers. Though if you do see an issue only with the native Julia solvers on this problem, please report that.

**Comment by honghuzi** [comment] 2017-07-20 08:44
I also wrote the serial version
```
    for i in 1:500000
        prob = ODEProblem(Eq, u0, (ti[i], 100.0))
        prob.u0[1] = x[i]; prob.u0[2] = y[i]; prob.u0[3] = px[i]; prob.u0[4] = py[i]; prob.u0[5] = act[i]
        sol = solve(prob; save_everystep=false, dense=false)
        x[i] = sol.u[2][1]
        y[i] = sol.u[2][2]
        px[i] = sol.u[2][3]
        py[i] = sol.u[2][4]
        act[i] = sol.u[2][5]
        if mod(i, Int(2e4)) == 0
            println("i=$(i)")
        end
    end
```
This for loop version takes about 79 s (4.5% gc time), while the above parallel monte carlo version takes 90 s, 171 s, 180 s when I choose the "parallel_type" argument as :threads, :parfor, :pmap (about 37 gc time).  
I tried  lsoda(), the operating system crashes for a serious memory overflow. This also happens when save_everystep=true is set.
Besides, I used the @code_warntype to profile the code, and found that there were so many red alert words where DifferentialEquations.jl was used.

**Comment by ChrisRackauckas** [comment] 2017-07-20 14:56
>I tried lsoda(), the operating system crashes for a serious memory overflow

That might not be threadsafe? I remember reading about that somewhere but never tested it.

>Besides, I used the @code_warntype to profile the code, and found that there were so many red alert words where DifferentialEquations.jl was used.

Parts of the solution likely won't be inferred but any of the solution values, i.e. the `.t` and `.u`, along with the interpolation, should be inferred (other fields might not infer as well, but those are deeper Julia issues which are being worked out in Base). This means that this shouldn't be affecting performance in a real way though. Of course, profile it with `@profile` and ProfileView.jl and please open an issue if you see anything of note.

>This for loop version takes about 79 s (4.5% gc time), while the above parallel monte carlo version takes 90 s, 171 s, 180 s when I choose the "parallel_type" argument as :threads, :parfor, :pmap (about 37 gc time).

The straight loop with no bells and whistles will and should be faster than `parallel_type = :none`, but I'm surprised it's that much faster. I've never seen threads slower. `@parfor` in Julia itself has issues and will likely be deprecated soon (from Julia) so I'm not too worried about that: not much I can do there. For `:pmap`: you're solving lots of very small equations, did you up the `pmap_batch_size` (this might only be on master?)? This is something you always need to do with `pmap` to make it more performant on lots of small evaluations, even outside of DiffEq. 

But the slow threads is worrisome. For sake of clarity, you set the environment variable before opening Julia and `Threads.nthreads()` gave an appropriate value?

Can you post a MWE?

**Comment by honghuzi** [comment] 2017-07-21 05:16
`But the slow threads is worrisome. For sake of clarity, you set the environment variable before opening Julia and Threads.nthreads() gave an appropriate value?`
Your are right. I forgot to add "export JULIA_NUM_THREADS=8" before running the code. When the environment variable is set, the "parallel_type=:none" calculation took only 31 s! 
In my situation, I just run the code on my own laptop. I think the best parallel type for me is :threads.
The project is:
[QTMC.tar.gz](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/1164508/QTMC.tar.gz)

**Comment by honghuzi** [comment] 2017-07-21 07:51
Although I added the "JULIA_NUM_THREADS=8" and set "parallel_type=:threads", the threading seems unstable: For the first time the code get acceleration. After that, I ran the code, and just got "segmentation fault", and never ran it correctly.

**Comment by ChrisRackauckas** [comment] 2017-07-21 18:28
A possibility of threading segfaults due to `#undef`s was noticed by @dextorious before, but I hadn't been able to reproduce that issue. On DiffEqMonteCarlo I think it might be fixed, but I cannot run your code because it's missing JLD files for the parameters. I changed the title to note that this is now the issue under investigation. If you can upload a runnable script that exhibits this issue that would be very helpful.

**Comment by honghuzi** [comment] 2017-07-22 05:46
`but I cannot run your code because it's missing JLD files for the parameters`
Uncomment the "@time Initial()", then "mkdir data" in the working directory, and the JLD files are obtained by running the "Initial()" function.

**Comment by honghuzi** [comment] 2017-07-22 07:07
Another unrelated question. How can I set the prob.tspan, so that the result of simulation give a time series as [0: dt: tmax]? I want the result at times with equal interval. That helps a lot in some conditions.

**Comment by ChrisRackauckas** [comment] 2017-07-24 16:31
>How can I set the prob.tspan, so that the result of simulation give a time series as [0: dt: tmax]? I want the result at times with equal interval. That helps a lot in some conditions.

`saveat=dt`.

**Comment by ChrisRackauckas** [comment] 2017-08-01 05:04
Finally got back around to this. Looks to not be directly in the integrators or anything like that, but in the setup. I could recreate the issue with a simpler example:

```julia
using DiffEqBase
ne =5; TT = 5000.0
Eq = (t,u,du) -> nothing
ti = rand(1500000)
px = rand(1500000)
y = rand(1500000)
w = rand(1500000)
x = zeros(ne)
py = zeros(ne)
act = zeros(ne)
u0 =  zeros(5)

#    for i in 1:ne
prob = ODEProblem(Eq, u0, (0, TT)) #Dummy allocate u0

function prob_func(prob, i)
    prob.u0 = [0.0, y[i], px[i], 0.0, 0.0]
    prob.tspan = (ti[i], TT)
    if mod(i, Int(2e4)) == 0
        println("i=$(i)")
    end
    prob
end

Threads.@threads for i in 1:length(y)
  prob_func(deepcopy(prob),i)
end 
```

This randomly will stall every once in awhile (for me, your code and this just stalls instead of killing Julia for some reason). This shows that just the multithreading on the prob_func creation was sufficient to stall Julia . That seems to suggest that `prob_func(deepcopy(prob),i)` is not thread-safe, but I have no idea why that would be the case. Here `prob` is not thread-local, but any modifications are made on the deepcopy version.

```julia
probs = [deepcopy(prob) for i in 1:Threads.nthreads()]

Threads.@threads for i in 1:length(y)
  prob_func(probs[Threads.threadid()],i)
end 
```

That also fails, which suggests it's not the `deepcopy` part, but instead `prob_func` itself which is not thread safe. However, I fail to see why that would be the case. Enclosed variables?

@dextorious was your `prob_func` similarly using enclosed variables?

**Comment by ChrisRackauckas** [comment] 2017-08-01 14:39
On Linux that same code gives me

```julia
signal (11): Segmentation fault
while loading console, in expression starting on line 2
jl_apply_generic at /usr/bin/../lib64/libjulia.so.0.6 (unknown line)
unknown function (ip: 0x7fccefa39d98)
unknown function (ip: 0xffffffffffffffff)
Allocations: 6797402 (Pool: 6795822; Big: 1580); GC: 15
```

so that definitely captures the issue. 

```juila
ne =5; TT = 5000.0
ti = rand(1500000)
px = rand(1500000)
y = rand(1500000)
w = rand(1500000)
x = zeros(ne)
py = zeros(ne)
act = zeros(ne)
u0 =  zeros(5)

function prob_func(i)
    u0 = [0.0, y[i], px[i], 0.0, 0.0]
    tspan = (ti[i], TT)
    if mod(i, Int(2e4)) == 0
        println("i=$(i)")
    end
    (u0,tspan)
end

Threads.@threads for i in 1:length(y)
  prob_func(i)
end 
```

That has no DiffEq but has a chance of segfaulting anyways. So this is an issue with Julia's multithreading.

**Comment by KristofferC** [comment] 2017-08-01 14:40
No IO allowed in threads.

**Comment by ChrisRackauckas** [comment] 2017-08-01 14:41
```julia
ne =5; TT = 5000.0
ti = rand(1500000)
px = rand(1500000)
y = rand(1500000)
w = rand(1500000)
x = zeros(ne)
py = zeros(ne)
act = zeros(ne)
u0 =  zeros(5)

function prob_func(i)
    u0 = [0.0, y[i], px[i], 0.0, 0.0]
    tspan = (ti[i], TT)
    (u0,tspan)
end

Threads.@threads for i in 1:length(y)
  prob_func(i)
end 
```

Thanks @KristofferC. That's it for sure. We should work around this by making progress monitoring for Monte Carlo solving. Opening an issue for that.

**Closed by ChrisRackauckas** 2017-08-01 14:41 UTC
