### ISSUE TITLE
installing DifferentialEquations error v0.4

### ISSUE THREAD

**Issue by ccontrer** [JuliaDiffEq/DifferentialEquations.jl#128] opened 2017-01-11 00:44 UTC
Hi, after installing and using DifferentialEquations I get
```
INFO: Precompiling module DifferentialEquations...
WARNING: New definition 
    push!(DataStructures.Accumulator{#T<:Any, #V<:Number}, #T<:Any) at /home/carlos/.julia/v0.4/DataStructures/src/accumulator.jl:54
is ambiguous with: 
    push!(Base.Associative, Base.Pair) at dict.jl:294.
To fix, define 
    push!(DataStructures.Accumulator{K<:Any, #V<:Number}, _<:Base.Pair)
before the new definition.
WARNING: New definition 
    write(Base.IO, ForwardDiff.Partials) at /home/carlos/.julia/v0.4/ForwardDiff/src/partials.jl:57
is ambiguous with: 
    write(Base.Base64.Base64EncodePipe, AbstractArray{UInt8, 1}) at base64.jl:89.
To fix, define 
    write(Base.Base64.Base64EncodePipe, ForwardDiff.Partials{N<:Any, UInt8})
before the new definition.
ERROR: LoadError: LoadError: Expression needs to be of form `a, b = c`
while loading /home/carlos/.julia/v0.4/DifferentialEquations/src/fem/fem_heatintegrators.jl, in expression starting on line 138
while loading /home/carlos/.julia/v0.4/DifferentialEquations/src/DifferentialEquations.jl, in expression starting on line 35
ERROR: Failed to precompile DifferentialEquations to /home/carlos/.julia/lib/v0.4/DifferentialEquations.ji
 in compilecache at ./loading.jl:400
```
I did `Pkg.update()`.
Thanks.

**Comment by ChrisRackauckas** [comment] 2017-01-11 00:54
Hey,
  The issue is that you are on Julia v0.4. I dropped support for v0.4 probably back in June and there are many things within the package that will not be compatible with v0.4. While you may be able to pin a bunch of packages to older versions (the specific error there would require pinning Parameters.jl to an older version), you'd need to scape up a very old form of the documentation, and most of the goodies have been implemented after that change. I would highly recommend upgrading to v0.5.

**Comment by ccontrer** [comment] 2017-01-11 00:58
Thanks @ChrisRackauckas. I was afraid of that. Will do.

**Comment by ChrisRackauckas** [comment] 2017-01-11 01:00
I am closing this issue because I will not be able to support v0.4. Sorry about the troubles.

**Closed by ChrisRackauckas** 2017-01-11 01:00 UTC
