### ISSUE TITLE
Bad performance and massive memory allocations when swapping function in integrator interface

### ISSUE THREAD

**Issue by janlisse** [JuliaDiffEq/DifferentialEquations.jl#491] opened 2019-08-27 14:56 UTC
For a fault simulation in a powergrid i use the integrator interface, to swap the ODEFunction f at a certain point in time. At a second point in time i restore the old function and solve the system of equations.
When i run this code i notice that it is orders of magnitude slower than other approaches (using a parameter p for changing the equations from within for example).
I have prepared a fully self-contained Jupyter notebook with benchmarks that show this.
The benchmarks also show that the function swapping code allocates massive amounts of memory. You can find & run the example here: https://mybinder.org/v2/gh/janlisse/minimal-fault-example/master?filepath=MinimalExample.ipynb
The code in question is mostly in the function simulate_switch_rhs().
Is this a bug?

**Comment by janlisse** [comment] 2019-08-28 13:07
@show for both functions yields:
```
ode_f1 = ODEFunction{true,NetworkEq,LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}(NetworkEq(1), LinearAlgebra.UniformScaling{Bool}(true), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing)
ode_f2 = ODEFunction{true,NetworkEq,LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}(NetworkEq(0.9), LinearAlgebra.UniformScaling{Bool}(true), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing)
```

**Comment by janlisse** [comment] 2019-08-28 13:27
That was also my first thought when i read the output from above. But changing it to a Float using Network(1.0) didn't make a difference.

**Comment by janlisse** [comment] 2019-08-28 15:52
If i add this line i get the following error:
```
ERROR: LoadError: type ODEIntegrator has no field uf
```

**Comment by janlisse** [comment] 2019-08-28 18:29
That seems to fix it! 
```
BenchmarkTools.Trial: 
  memory estimate:  3.23 MiB
  allocs estimate:  42908
  --------------
  minimum time:     3.470 ms (0.00% GC)
  median time:      3.854 ms (0.00% GC)
  mean time:        4.735 ms (14.82% GC)
  maximum time:     11.366 ms (49.06% GC)
  --------------
  samples:          1054
  evals/sample:     1
```
You are my man! Shall i create a PR for that or will you make the change by yourself?

**Comment by devmotion** [comment] 2019-08-28 18:59
> should we just add this into the nlsolver?

What do you mean? How is this issue related to the nonlinear solvers?

If I understand correctly, the problem is that swapping the function of the integrator during the integration leads to bad performance. It's not strictly typed (otherwise it wouldn't be possible at all), which I assume already causes some performance regressions. Unsurprisingly there are more issues since certain parts of the cache depend on the function but are (currently) only initialized once when the integrator is initialized. So it seems, if we want to support such a use case, we should probably provide a function `set_f!(integrator, f)`, that takes care of correcting some of the caches (I don't think we would have to do that every time we call `perform_step!`?), similar to `set_dt!` and so on?

**Comment by ChrisRackauckas** [comment] 2019-08-29 12:30
Whenever we call the differentiation we change `p` and `t` and such, why not make sure was pass along `f` too? Seems like a natural way to handle it.

**Comment by devmotion** [comment] 2019-08-29 13:17
Yes that's definitely something we could do. But that's not related to the non-linear solvers but just to the implementation of calc_J and calc_J!, it seems?

**Comment by ChrisRackauckas** [comment] 2019-08-29 13:22
Oh yes, that's where the change would go. I forgot whether that part was moved with the recent nonlinear solver changes.

**Comment by janlisse** [comment] 2019-10-01 21:50
Any updates on this?

**Comment by devmotion** [comment] 2019-10-01 22:52
The proposed change was included in OrdinaryDiffEq some time ago, we've added lines https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/8b5af68ee4126d3772fe690a7128468f1334b4d6/src/derivative_utils.jl#L55 and
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/8b5af68ee4126d3772fe690a7128468f1334b4d6/src/derivative_utils.jl#L95. Have you checked if your issue is resolved in the latest version of OrdinaryDiffEq (it should even work in some previous versions)?

**Comment by ChrisRackauckas** [comment] 2019-10-02 07:22
Yup this should be fixed, just forgot to close the issue. Thanks for the report, and let us know if you run into anything else.

**Closed by ChrisRackauckas** 2019-10-02 07:22 UTC
