### ISSUE TITLE
Solution unstable with DP5, success with dopri5

### ISSUE THREAD

**Issue by SirLukeSchande** [JuliaDiffEq/DifferentialEquations.jl#470] opened 2019-06-18 10:03 UTC
I'm working on the following system of differential equations:

```
dL_i(t)/dt = r*L_i(t) * (1 - r/K * Y_i(t) - c * sum(L_j(t), j != i))
dY_i(t)/dt = L_i(t) - a * Y_i(t)
```
where i,j = 1,...,300. I get the `retcode=Unstable` using DP5 (also for Tsit5). Using dopri5 from ODEInterfaceDiffEq.jl I get `retcode=Success` and the solution is similar to the one from Ros4LStab. I don't understand why this happens. 

Has anybody an idea where the difference stems from?

Thanks in advance.

**Comment by ChrisRackauckas** [comment] 2019-06-20 11:27
Can you share a code that demonstrates the issue?

**Comment by ChrisRackauckas** [comment] 2019-08-05 17:03
Closing since there's no code to reproduce the issue. Feel free to share if there is.

**Closed by ChrisRackauckas** 2019-08-05 17:03 UTC
