### ISSUE TITLE
Upgrade to Julia v0.5.2 The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#170] opened 2017-05-12 09:05 UTC
Just upgrade to Julia v0.5.2, Pkg.add("DifferentialEquations") and Pkg.test("DifferentialEquations") passed. At the following comand:

#function lorenz(t, u, du)
#    du[1] = 10.0(u[2]-u[1])
#    du[2] = u[1]*(28.0-u[3]) - u[2]
#    du[3] = u[1]*u[2] - (8/3)*u[3]
#end

lorenz = @ode_def Lorenz begin
  dx = σ*(y-x)
  dy = ρ*x-y-x*z
  dz = x*y-β*z
end σ = 10. β = 8./3. ρ => 28.

The kernel dies and does not restart. Something to do with @ode_def. The commented version above is working fine.

**Comment by ChrisRackauckas** [comment] 2017-05-12 09:12
Seems like your SymEngine didn't upgrade properly and symengine 0.2.0 segfaults when it hits unicode. What OS is this? And what happens if you `Pkg.build("SymEngine")`?

@isuruf

**Comment by finmod** [comment] 2017-05-12 09:18
This is Windows. Pkg.build("SymEngine"), Pkg.test("SymEngine") and Pkg.status() below:
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.2 (2017-05-06 16:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.build("SymEngine")
INFO: Building Conda
INFO: Building SymEngine

julia> Pkg.test("SymEngine")
INFO: Testing SymEngine
(1/2)*x - 5*x*y + x^2
1/2 + 2*x - 5*y
INFO: SymEngine tests passed

julia> Pkg.status()
9 required packages:
 - BlackBoxOptim                 0.2.1+             master
 - DifferentialEquations         2.2.0
 - Gtk                           0.13.0
 - IJulia                        1.5.0
 - Juno                          0.2.7
 - LeastSquaresOptim             0.2.1
 - Plots                         0.11.1
 - ProgressMeter                 0.3.4
 - PyPlot                        2.3.2
91 additional packages:
 - AlgebraicDiffEq               0.1.0
 - BaseTestNext                  0.2.2
 - BinDeps                       0.4.7
 - BufferedStreams               0.3.2
 - CPUTime                       0.0.5
 - Cairo                         0.3.0
 - Calculus                      0.2.2
 - ChunkedArrays                 0.1.1
 - ColorTypes                    0.5.0
 - Colors                        0.7.3
 - Combinatorics                 0.4.0
 - Compat                        0.24.0
 - Conda                         0.5.3
 - DataStructures                0.5.3
 - DelayDiffEq                   0.3.0
 - DiffBase                      0.1.0
 - DiffEqBase                    1.5.0
 - DiffEqBiological              0.0.1
 - DiffEqCallbacks               0.1.1
 - DiffEqDevTools                0.8.1
 - DiffEqFinancial               0.2.0
 - DiffEqJump                    0.3.1
 - DiffEqMonteCarlo              0.4.0
 - DiffEqNoiseProcess            0.1.0
 - DiffEqPDEBase                 0.3.1
 - DiffEqParamEstim              0.3.0
 - DiffEqSensitivity             0.2.2
 - DiffEqUncertainty             0.0.1
 - DimensionalPlotRecipes        0.0.2
 - Distances                     0.4.1
 - Distributions                 0.12.5
 - EllipsisNotation              0.1.0
 - FiniteElementDiffEq           0.3.0
 - FixedPointNumbers             0.3.7
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.4.2
 - GenericSVD                    0.0.2
 - Graphics                      0.2.0
 - Hiccup                        0.1.1
 - InplaceOps                    0.1.0
 - IterativeSolvers              0.2.2
 - Iterators                     0.3.1
 - JSON                          0.11.0
 - LaTeXStrings                  0.2.1
 - LearnBase                     0.1.5
 - LibExpat                      0.2.5
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - LossFunctions                 0.0.3
 - LsqFit                        0.2.0
 - MacroTools                    0.3.6
 - MbedTLS                       0.4.5
 - Measures                      0.1.0
 - Media                         0.2.7
 - MultiScaleArrays              0.2.0
 - NLsolve                       0.9.1
 - NaNMath                       0.2.4
 - Optim                         0.7.8
 - OrdinaryDiffEq                2.1.0
 - PDMats                        0.6.0
 - ParameterizedFunctions        2.0.0
 - Parameters                    0.7.2
 - PlotThemes                    0.1.3
 - PlotUtils                     0.4.1
 - PolynomialFactors             0.0.4
 - Polynomials                   0.1.5
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.3
 - PyCall                        1.12.0
 - QuadGK                        0.1.2
 - Ranges                        0.0.1
 - RecipesBase                   0.1.0
 - RecursiveArrayTools           0.6.1
 - Reexport                      0.0.3
 - ResettableStacks              0.1.0
 - Rmath                         0.1.6
 - Roots                         0.3.1
 - SHA                           0.3.2
 - Showoff                       0.1.1
 - SimpleTraits                  0.5.0
 - SpecialFunctions              0.1.1
 - StatsBase                     0.14.1
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.0.3
 - Sundials                      0.11.1
 - SymEngine                     0.2.0
 - URIParser                     0.1.8
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.2.3
 - ZMQ                           0.4.2

julia>

**Comment by ChrisRackauckas** [comment] 2017-05-12 09:23
Can you post `SymEngine.libversion`? That should be 0.3.0. If it's 0.2.0, then that's the issue.

**Comment by finmod** [comment] 2017-05-12 09:49
SymEngine.libversion >= VersionNumber("0.2.0") answers true and SymEngine.libversion >= VersionNumber("0.3.0") also true

**Comment by ChrisRackauckas** [comment] 2017-05-12 13:23
So SymEngine is keeping the old version, and using the old version? That's really not good. We'll need @isuruf to comment.

**Comment by isuruf** [comment] 2017-05-12 13:25
It's using the new version if `SymEngine.libversion >= VersionNumber("0.3.0")` returns true. `SymEngine.libversion >= VersionNumber("0.2.0")` is true for both versions.

Can you format the code with backticks?

**Comment by ChrisRackauckas** [comment] 2017-05-12 21:01
Did you ever get to the bottom of this? I know that if someone uses pre-SymEngine.jl 0.2.0 it will (reliably) segfault like this. But on 3 OS's I believe @isuruf @ScottPJones and I tried this out, and Travis + AppVeyor says this (ParameterizedFunctions.jl 2.0.0 with unicode) should not segfault with the new version of SymEngine. So, given that there hasn't been a feature release so tested to not have this issue, I'm befuddled as to how it could show up, unless there's a SymEngine installation error lurking in here.

**Comment by finmod** [comment] 2017-05-12 21:49
No luck, no solution so far. It always die when @ode_def and the model is executed.

**Comment by ChrisRackauckas** [comment] 2017-05-13 00:09
Can you delete your precompilation cache and restart Julia?

**Comment by ChrisRackauckas** [comment] 2017-05-13 11:20
Delete SymEngine and reinstall it. See what happens?

**Comment by finmod** [comment] 2017-05-13 14:06
Same outcome after the following sequence:

Pkg.rm("SymEngine") twice, the first unregistered
Pkg.update() re-install SymEngine 0.2.0
perhaps need some pinning

The Pkg.free("DiffEqParamEstim")
This re-install SymEngine 0.2.0

Pkg.update() re-install SymEngine 0.2.0

Here is Pkg.status()

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.2 (2017-05-06 16:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.status()
12 required packages:
 - BlackBoxOptim                 0.2.1+             master
 - DifferentialEquations         2.2.0
 - ExcelReaders                  0.7.0
 - Gtk                           0.13.0
 - IJulia                        1.5.0
 - Juno                          0.2.7
 - LeastSquaresOptim             0.2.1
 - LowRankModels                 0.2.0
 - MultivariateStats             0.4.0
 - Plots                         0.11.2
 - ProgressMeter                 0.3.4
 - PyPlot                        2.3.2
100 additional packages:
 - AlgebraicDiffEq               0.1.0
 - ArrayViews                    0.6.4
 - BaseTestNext                  0.2.2
 - BinDeps                       0.5.0
 - BufferedStreams               0.3.2
 - CPUTime                       0.0.5
 - Cairo                         0.3.0
 - Calculus                      0.2.2
 - ChunkedArrays                 0.1.1
 - ColorTypes                    0.5.0
 - Colors                        0.7.3
 - Combinatorics                 0.4.0
 - Compat                        0.25.0
 - Conda                         0.5.3
 - DataArrays                    0.3.12
 - DataFrames                    0.9.1
 - DataStructures                0.5.3
 - Dates                         0.4.4
 - DelayDiffEq                   0.4.0
 - DiffBase                      0.1.0
 - DiffEqBase                    1.5.1
 - DiffEqBiological              0.0.1
 - DiffEqCallbacks               0.1.1
 - DiffEqDevTools                0.8.1
 - DiffEqFinancial               0.2.0
 - DiffEqJump                    0.3.1
 - DiffEqMonteCarlo              0.4.0
 - DiffEqNoiseProcess            0.1.0
 - DiffEqPDEBase                 0.3.1
 - DiffEqParamEstim              0.3.0
 - DiffEqSensitivity             0.2.2
 - DiffEqUncertainty             0.0.1
 - DimensionalPlotRecipes        0.0.2
 - Distances                     0.4.1
 - Distributions                 0.12.5
 - EllipsisNotation              0.1.0
 - FileIO                        0.3.1
 - FiniteElementDiffEq           0.3.0
 - FixedPointNumbers             0.3.7
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.4.2
 - GZip                          0.3.0
 - GenericSVD                    0.0.2
 - Graphics                      0.2.0
 - Hiccup                        0.1.1
 - InplaceOps                    0.1.0
 - IterativeSolvers              0.2.2
 - Iterators                     0.3.1
 - JSON                          0.11.0
 - LaTeXStrings                  0.2.1
 - LearnBase                     0.1.5
 - LibExpat                      0.2.5
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - LossFunctions                 0.0.3
 - LsqFit                        0.2.0
 - MacroTools                    0.3.6
 - MbedTLS                       0.4.5
 - Measures                      0.1.0
 - Media                         0.2.7
 - MultiScaleArrays              0.2.0
 - NLsolve                       0.9.1
 - NMF                           0.2.5
 - NaNMath                       0.2.4
 - Optim                         0.7.8
 - OrdinaryDiffEq                2.1.0
 - PDMats                        0.6.0
 - ParameterizedFunctions        2.0.0
 - Parameters                    0.7.2
 - PlotThemes                    0.1.3
 - PlotUtils                     0.4.1
 - PolynomialFactors             0.0.4
 - Polynomials                   0.1.5
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.3
 - PyCall                        1.12.0
 - QuadGK                        0.1.2
 - Ranges                        0.0.1
 - RecipesBase                   0.1.0
 - RecursiveArrayTools           0.6.1
 - Reexport                      0.0.3
 - ResettableStacks              0.1.0
 - Rmath                         0.1.6
 - Roots                         0.3.1
 - SHA                           0.3.2
 - ScikitLearnBase               0.3.0
 - Showoff                       0.1.1
 - SimpleTraits                  0.5.0
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.1.1
 - StatsBase                     0.14.1
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.0.4
 - Sundials                      0.11.1
 - SymEngine                     0.2.0
 - URIParser                     0.1.8
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.2.4
 - ZMQ                           0.4.2

julia>

**Comment by ChrisRackauckas** [comment] 2017-05-13 14:20
Geez, I'm baffled. What happens if you nuke your `/.julia` and start over? Could you do that?

**Comment by isuruf** [comment] 2017-05-13 14:27
Can you try something like,
```
using SymEngine
print(SymEngine.libversion)
print(SymEngine.Basic("ρ"))
```

**Comment by finmod** [comment] 2017-05-13 18:57
Here it is:

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.2 (2017-05-06 16:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using SymEngine

julia> print(SymEngine.libversion)
0.3.0
julia> print(SymEngine.Basic("p"))
p
julia>

**Comment by ChrisRackauckas** [comment] 2017-05-13 19:00
Interesting. Could you run:

```julia
lorenz = @ode_def Lorenz begin
dx = sigma*(y-x)
dy = rho*x-y-x*z
dz = x*y-beta*z
end sigma = 10. beta = 8./3. rho => 28.
```

? Pull out the implicit multiplications and the Unicode, and then put them back in one-by-one and see if we can find out what's the cause.

**Comment by ChrisRackauckas** [comment] 2017-05-13 19:00
Actually, after this change now I get a SymEngine segfault. Hold on.

**Comment by ChrisRackauckas** [comment] 2017-05-13 19:02
```julia
using ParameterizedFunctions
lorenz = @ode_def Lorenz begin
dx = σ*(y-x)
dy = ρx-y-xz
dz = xy-βz
end σ = 10. β = 8./3. ρ => 28.
```

works fine for me, but 

```julia
lorenz = @ode_def Lorenz begin
dx = sigma*(y-x)
dy = rho*x-y-x*z
dz = x*y-beta*z
end sigma = 10. beta = 8./3. rho => 28.
```

kills Julia inside of SymEngine:

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffef12c3642 -- 
basic_diff at C:\Users\Chris\.julia\v0.5\SymEngine\deps\symengine-0.3.0\bin\symengine-0.3.dll (unknown line)
while loading console, in expression starting on line 1
basic_diff at C:\Users\Chris\.julia\v0.5\SymEngine\deps\symengine-0.3.0\bin\symengine-0.3.dll (unknown line)
diff at C:\Users\Chris\.julia\v0.5\SymEngine\src\calculus.jl:12
unknown function (ip: 000000002104B0BA)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
diff at C:\Users\Chris\.julia\v0.5\SymEngine\src\calculus.jl:22
collect_to! at .\array.jl:340
collect_to_with_first! at .\array.jl:327
unknown function (ip: 000000002104B279)
collect at .\array.jl:308
#ode_def_opts#1 at C:\Users\Chris\.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:91
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1388 [inlined]
jl_f__apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:547
ode_def_opts at C:\Users\Chris\.julia\v0.5\ParameterizedFunctions\src\ode_def_opts.jl:4
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1388 [inlined]
jl_f__apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:547
@ode_def at C:\Users\Chris\.julia\v0.5\ParameterizedFunctions\src\macros.jl:11
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
fl_invoke_julia_macro at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:161
apply_cl at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:1227
_applyn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:683
fl_map1 at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:2220
apply_cl at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:1177
do_trycatch at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:899
apply_cl at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:1807
_applyn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:683
fl_applyn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:723
jl_parse_eval_all at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:702
include_string at .\loading.jl:441
unknown function (ip: 0000000061EDEB95)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:66
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:190
eval_body at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:469
jl_interpret_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:573
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:572 [inlined]
jl_toplevel_eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:580
jl_toplevel_eval_in_warn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:590
eval at .\boot.jl:234
unknown function (ip: 0000000061C4C015)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
#65 at C:\Users\Chris\.julia\v0.5\Atom\src\eval.jl:102
withpath at C:\Users\Chris\.julia\v0.5\CodeTools\src\utils.jl:30
unknown function (ip: 0000000021005D76)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
withpath at C:\Users\Chris\.julia\v0.5\Atom\src\eval.jl:38
unknown function (ip: 00000000210059E6)
macro expansion at C:\Users\Chris\.julia\v0.5\Atom\src\eval.jl:101 [inlined]
#64 at .\task.jl:60
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:211 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1950
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1388 [inlined]
start_task at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:254
Allocations: 8266496 (Pool: 8265242; Big: 1254); GC: 13
```

I'll try and get an example out.

**Comment by ChrisRackauckas** [comment] 2017-05-13 19:30
```julia
ex = :(x * y - (8 ./ 3.0) * z)
using SymEngine; SymEngine.Basic(ex)
```

and

```julia 
using ParameterizedFunctions
lorenz = @ode_def Lorenz begin
dx = sigma*(y-x)
dy = rho*x-y-x*z
dz = x*y-beta*z
end sigma = 10.0 beta = 8.0/3.0 rho => 28.
```

is fine. Notice

```
@which 8./3.
./(x::Number, y::Number) at operators.jl:148
```


SymEngine cannot handle the `./` operator and it segfaults when it sees it.

**Comment by finmod** [comment] 2017-05-13 19:30
Well spotted. it is the 8./3. that creates the problem with 2.6666 it works.

**Comment by ChrisRackauckas** [comment] 2017-05-13 19:32
Now, how to handle this is a different story. Could SymEngine conceivably handle changing dot-operators to scalar operators on its end?

**Comment by isuruf** [comment] 2017-05-13 19:40
We could walk the expression tree and replace the dot operators before sending it to julia.
Also why is `8./3.` parsed to `8 ./3.0 instead of `8.0/3.0` ?
This sometimes changes the types. For instance `8.*2` and `8.0*2` have 2 different results

**Comment by ScottPJones** [comment] 2017-05-14 18:03
I think that the idea (from the Julia core team) is that normally you should have .0 instead of . for fp constants, and if you want the ./ operator, it's a good idea to always put spacs around it.

**Comment by ChrisRackauckas** [comment] 2017-05-14 18:04
I think they should just deprecate it. `8.` looks bad to me, and has ambiguous parsing. Just use `8.0`.

**Comment by ChrisRackauckas** [comment] 2017-05-15 20:57
I am going to close this as duplicate of https://github.com/symengine/SymEngine.jl/issues/80 . If SymEngine throws an error here, I think that's a good fix. Or I would prefer that Julia's parser was different and didn't allow `8.`. However, I wouldn't want to muck with the parsing myself. I don't think it's a good idea to write something that "goes around" the parser to fix this case: that's likely to introduce more bugs than it fixes. Hopefully, this is a fringe issue that doesn't show up often.

**Closed by ChrisRackauckas** 2017-05-15 20:57 UTC
