### ISSUE TITLE
Double callback crossing floating pointer reducer errored.

### ISSUE THREAD

**Issue by astrorCoder** [JuliaDiffEq/DifferentialEquations.jl#430] opened 2019-02-28 09:48 UTC
Depending on the input that I use in the ODE problem sometimes this error happens, but if I repeat the call to the same problem after that the it doesn't happen again. It is very weird and I cannot find anything like this. Some help? Here is the complete error code:

**ERROR: Double callback crossing floating pointer reducer errored. Report this issue.**
Stacktrace:
 [1] find_callback_time(::OrdinaryDiffEq.ODEIntegrator{Tsit5,false,Array{Float64,1},Float64,Array{Any,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1},Float64}, ::ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}, ::Int64) at /home/astror/.julia/packages/DiffEqBase/cPqrj/src/callbacks.jl:266
 [2] find_first_continuous_callback at /home/astror/.julia/packages/DiffEqBase/cPqrj/src/callbacks.jl:141 [inlined]
 [3] handle_callbacks!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,false,Array{Float64,1},Float64,Array{Any,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1},Float64}) at /home/astror/.julia/packages/OrdinaryDiffEq/miOSH/src/integrators/integrator_utils.jl:372
 [4] loopfooter!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,false,Array{Float64,1},Float64,Array{Any,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1},Float64}) at /home/astror/.julia/packages/OrdinaryDiffEq/miOSH/src/integrators/integrator_utils.jl:332
 [5] solve!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,false,Array{Float64,1},Float64,Array{Any,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(opnorm),CallbackSet{Tuple{ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1},Float64}) at /home/astror/.julia/packages/OrdinaryDiffEq/miOSH/src/solve.jl:346
 [6] #__solve#257(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:dense, :save_everystep),Tuple{Bool,Bool}}}, ::Function, ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem}, ::Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /home/astror/.julia/packages/OrdinaryDiffEq/miOSH/src/solve.jl:7
 [7] #__solve at ./none:0 [inlined] (repeats 5 times)
 [8] #solve#429(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:dense, :save_everystep),Tuple{Bool,Bool}}}, ::Function, ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem}, ::Tsit5) at /home/astror/.julia/packages/DiffEqBase/cPqrj/src/solve.jl:39
 [9] (::getfield(DiffEqBase, Symbol("#kw##solve")))(::NamedTuple{(:dense, :save_everystep),Tuple{Bool,Bool}}, ::typeof(solve), ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},false,Array{Any,1},ODEFunction{false,typeof(dineq),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing},DiffEqBase.StandardODEProblem}, ::Tsit5) at ./none:0
 [10] calc_data(::Array{Float64,2}, ::Dict{String,Float64}, ::Dict{String,Any}, ::ContinuousCallback{typeof(gCondition),Nothing,typeof(impulse!),typeof(DiffEqBase.INITIALIZE_DEFAULT),Float64,Int64,Nothing}) at /home/astror/HDDs/TOP/MEGA/Universidad/Julia/test3.jl:42
 [11] calc_data(::Array{Float64,2}, ::Dict{String,Float64}, ::Dict{String,Any}) at /home/astror/HDDs/TOP/MEGA/Universidad/Julia/test3.jl:41 (repeats 3 times)
 [12] repetir(::Int64) at /home/astror/HDDs/TOP/MEGA/Universidad/Julia/test3.jl:61
 [13] top-level scope at none:0

It is my first time using this page so sorry if it is not the correct way to report an issue, anything needed I will send it, thanks.

**Comment by ChrisRackauckas** [comment] 2019-02-28 14:56
It's a 1 in a million floating point issue. Do you have code I can run? I can tweak the heuristics to be more robust.

**Comment by astrorCoder** [comment] 2019-03-01 09:32
Thanks Chris for the fast response and wanting to help. I have managed to change my code so that this problem doesn't happen any more, and there was actually a problem with the logic in the Callback that I didn't notice and it wasn't doing what I intended. There is still an issue and it is that I don't understand why this error occurred. I have prepared a script that you can run if you want to, here
[testGithub.jl.zip](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2918789/testGithub.jl.zip)

I have been using Julia for a week and I am far from ready to understand whats going on so I don't know if I can help with this, if you need anything else just tell my and I'll do what I can. Thanks again¡

**Comment by ChrisRackauckas** [comment] 2019-03-01 21:56
Thanks! I fixed it and it's tagged in DiffEqBase v5.4.1 which will be released shortly.

**Closed by ChrisRackauckas** 2019-03-01 21:56 UTC

**Comment by astrorCoder** [comment] 2019-03-03 08:32
Awesome!

**Comment by tkf** [comment] 2019-04-10 05:45
@ChrisRackauckas I see this error sometimes when I try OrdinaryDiffEq's "Cache Tests" while AOT-compiling it.  For example:

https://travis-ci.com/tkf/julia-sysimage-recipes/jobs/191697584#L546
https://travis-ci.com/tkf/julia-sysimage-recipes/jobs/191707801#L478

I'm not sure if is related to that OrdinaryDiffEq is in the system image, though.  Also, sometime tests pass even when running Travis with exactly the same commit (but maybe that's because random seed is not fixed or something?).

**Comment by ChrisRackauckas** [comment] 2019-04-10 11:11
That's just a very random test. It's a test of a system that can go unstable with the wrong random numbers. We need to make it a bit simpler... I think Yingbo did not too long ago.

**Comment by tkf** [comment] 2019-04-10 16:03
OK. I'm glad that it's not a bug :)
