### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaDiffEq/DifferentialEquations.jl#497] opened 2019-09-02 23:56 UTC
Since you are usually not merging till tests pass, FYI:
```julia
(v1.2) pkg> test DifferentialEquations
   Testing DifferentialEquations
 Resolving package versions...
 Installed SafeTestsets ──────────── v0.0.1
 Installed DiffEqProblemLibrary ──── v4.5.1
 Installed StaticPolynomials ─────── v1.3.2
 Installed ModelingToolkit ───────── v0.6.4
 Installed DiffEqBiological ──────── v3.9.1
 Installed DynamicPolynomials ────── v0.3.3
 Installed DiffEqOperators ───────── v4.1.0
 Installed PrettyTables ──────────── v0.5.1
 Installed Polynomials ───────────── v0.5.2
 Installed ProjectiveVectors ─────── v0.2.2
 Installed SymEngine ─────────────── v0.7.0
 Installed Crayons ───────────────── v4.0.0
 Installed Formatting ────────────── v0.4.0
 Installed FixedPolynomials ──────── v0.4.0
 Installed Quadmath ──────────────── v0.5.0
 Installed NNlib ─────────────────── v0.6.0
 Installed MixedSubdivisions ─────── v0.3.2
 Installed MultivariatePolynomials ─ v0.3.2
 Installed ProgressMeter ─────────── v1.0.0
 Installed HomotopyContinuation ──── v1.1.1
 Installed DoubleFloats ──────────── v0.9.7
 Installed DataValueInterfaces ───── v1.0.0
 Installed GenericSchur ──────────── v0.2.3
 Installed ElasticArrays ─────────── v0.4.0
 Installed TimerOutputs ──────────── v0.5.0
 Installed Tables ────────────────── v0.2.11
  Building SymEngine → `~/.julia/packages/SymEngine/zSUGO/deps/build.log`
    Status `/var/folders/qy/yrp8ty0d77sd4ghs1sxdwt0w0000gp/T/jl_F4UkFA/Manifest.toml`
  [79e6a3ab] Adapt v1.0.0
  [ec485272] ArnoldiMethod v0.0.4
  [4fba245c] ArrayInterface v1.2.1
  [aae01518] BandedMatrices v0.10.1
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.6
  [8e7c35d0] BlockArrays v0.9.1
  [ffab5731] BlockBandedMatrices v0.4.6
  [764a87c0] BoundaryValueDiffEq v2.3.0
  [00ebfdb7] CSTParser v0.6.2
  [49dc2e85] Calculus v0.5.0
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [a8cc5b0e] Crayons v4.0.0
  [9a962f9c] DataAPI v1.0.1
  [864edb3b] DataStructures v0.17.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [bcd4f6db] DelayDiffEq v5.14.0
  [2b5f629d] DiffEqBase v5.20.0
  [eb300fae] DiffEqBiological v3.9.1
  [459566f4] DiffEqCallbacks v2.8.0
  [01453d9d] DiffEqDiffTools v1.3.0
  [5a0ffddc] DiffEqFinancial v2.1.0
  [c894b116] DiffEqJump v6.2.0
  [77a26b50] DiffEqNoiseProcess v3.3.1
  [9fdde737] DiffEqOperators v4.1.0
  [055956cb] DiffEqPhysics v3.2.0
  [a077e3f3] DiffEqProblemLibrary v4.5.1
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [0c46a032] DifferentialEquations v6.6.0
  [c619ae07] DimensionalPlotRecipes v0.2.0
  [b4f34e82] Distances v0.8.2
  [ffbed154] DocStringExtensions v0.8.0
  [497a8b3b] DoubleFloats v0.9.7
  [7c1d4256] DynamicPolynomials v0.3.3
  [fdbdab4c] ElasticArrays v0.4.0
  [d4d017d3] ExponentialUtilities v1.5.1
  [1a297f60] FillArrays v0.6.4
  [3dd14ad9] FixedPolynomials v0.4.0
  [59287772] Formatting v0.4.0
  [f6369f11] ForwardDiff v0.10.3
  [069b7b12] FunctionWrappers v1.0.0
  [01680d73] GenericSVD v0.2.1
  [c145ed77] GenericSchur v0.2.3
  [f213a82b] HomotopyContinuation v1.1.1
  [d25df0c9] Inflate v0.1.1
  [42fd0dbc] IterativeSolvers v0.8.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [5078a376] LazyArrays v0.10.0
  [093fc24a] LightGraphs v1.3.0
  [d3d80556] LineSearches v7.0.1
  [1914dd2f] MacroTools v0.5.1
  [a3b82374] MatrixFactorizations v0.1.0
  [291d046c] MixedSubdivisions v0.3.2
  [961ee093] ModelingToolkit v0.6.4
  [46d2c3a1] MuladdMacro v0.2.1
  [f9640e96] MultiScaleArrays v1.5.0
  [102ac46a] MultivariatePolynomials v0.3.2
  [d41bc354] NLSolversBase v7.4.1
  [2774e3e8] NLsolve v4.1.0
  [872c559c] NNlib v0.6.0
  [77ba4419] NaNMath v0.3.2
  [bac558e1] OrderedCollections v1.1.0
  [1dea7af3] OrdinaryDiffEq v5.15.0
  [d96e819e] Parameters v0.11.0
  [e409e4f3] PoissonRandom v0.4.0
  [f27b6e38] Polynomials v0.5.2
  [08abe8d2] PrettyTables v0.5.1
  [92933f4c] ProgressMeter v1.0.0
  [01f381cc] ProjectiveVectors v0.2.2
  [be4d8f0f] Quadmath v0.5.0
  [e6cf234a] RandomNumbers v1.3.0
  [3cdcf5f2] RecipesBase v0.7.0
  [731186ca] RecursiveArrayTools v1.0.2
  [f2c3362d] RecursiveFactorization v0.1.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [ae5879a3] ResettableStacks v0.6.0
  [f2b01f46] Roots v0.8.3
  [1bc83da4] SafeTestsets v0.0.1
  [699a6c99] SimpleTraits v0.9.0
  [47a9eef4] SparseDiffTools v0.9.0
  [276daf66] SpecialFunctions v0.8.0
  [90137ffa] StaticArrays v0.11.0
  [62e018b1] StaticPolynomials v1.3.2
  [9672c7b4] SteadyStateDiffEq v1.5.0
  [789caeaf] StochasticDiffEq v6.9.0
  [c3572dad] Sundials v3.6.2
  [123dc426] SymEngine v0.7.0
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v0.2.11
  [a759f4b9] TimerOutputs v0.5.0
  [0796e94c] Tokenize v0.5.6
  [a2a6695c] TreeViews v0.3.0
  [30578b45] URIParser v0.4.0
  [19fa3120] VertexSafeGraphs v0.1.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [4607b0f0] SuiteSparse  [`@stdlib/SuiteSparse`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
Starting tests
Test Summary:              | Pass  Total
Default Discrete Algorithm |    1      1
  3.064186 seconds (13.37 M allocations: 699.063 MiB, 5.90% gc time)
Test Summary:         | Pass  Total
Default ODE Algorithm |   21     21
 81.338029 seconds (323.67 M allocations: 14.583 GiB, 7.98% gc time)
Test Summary:                  | Pass  Total
Default Steady State Algorithm |    1      1
  5.297064 seconds (28.54 M allocations: 1.531 GiB, 11.79% gc time)
Test Summary:         | Pass  Total
Default SDE Algorithm |    8      8
 63.870492 seconds (153.13 M allocations: 27.102 GiB, 6.71% gc time)
Test Summary:          | Pass  Total
Default RODE Algorithm |    1      1
  5.687763 seconds (23.23 M allocations: 7.141 GiB, 13.18% gc time)
Default DDE Algorithm: Error During Test at /Users/abradley/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:25
  Got exception outside of a @test
  LoadError: MethodError: alg_cache(::CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}}, ::Float64, ::Float64, ::Type{Float64}, ::Type{Float64}, ::Type{Float64}, ::Float64, ::Float64, ::DelayDiffEq.ODEFunctionWrapper{false,getfield(Main.##438, Symbol("##1#2")),getfield(Main.##438, Symbol("##3#4")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}, ::Float64, ::Float64, ::Float64, ::Nothing, ::Bool, ::Type{Val{false}}) is ambiguous. Candidates:
    alg_cache(alg::Union{OrdinaryDiffEqAlgorithm, OrdinaryDiffEq.DAEAlgorithm}, u, rate_prototype, uEltypeNoUnits, uBottomEltypeNoUnits, tTypeNoUnits, uprev, uprev2, f, t, dt, reltol, p, calck, ::Type{Val{iip}}) where iip in OrdinaryDiffEq at deprecated.jl:65
    alg_cache(alg::CompositeAlgorithm, u, rate_prototype, uEltypeNoUnits, uBottomEltypeNoUnits, tTypeNoUnits, uprev, uprev2, f, t, dt, reltol, p, calck, iip) in OrdinaryDiffEq at /Users/abradley/.julia/packages/OrdinaryDiffEq/3asqQ/src/caches/basic_caches.jl:14
  Possible fix, define
    alg_cache(::CompositeAlgorithm, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Type{Val{iip}})
  Stacktrace:
   [1] #build_history_function#32(::Float64, ::Bool, ::Bool, ::Function, ::typeof(DelayDiffEq.build_history_function), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}, ::Float64, ::Float64) at /Users/abradley/.julia/packages/DelayDiffEq/nHoER/src/utils.jl:294
   [2] (::getfield(DelayDiffEq, Symbol("#kw##build_history_function")))(::NamedTuple{(:dt, :adaptive, :internalnorm),Tuple{Float64,Bool,typeof(DiffEqBase.ODE_DEFAULT_NORM)}}, ::typeof(DelayDiffEq.build_history_function), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}, ::Float64, ::Float64) at ./none:0
   [3] #__init#21(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Discontinuity{Float64},1}, ::Nothing, ::Bool, ::Bool, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Float64, ::Float64, ::Float64, ::Bool, ::Bool, ::Rational{Int64}, ::Nothing, ::Nothing, ::Rational{Int64}, ::Int64, ::Int64, ::Int64, ::Rational{Int64}, ::Bool, ::Int64, ::Nothing, ::Nothing, ::Int64, ::typeof(DiffEqBase.ODE_DEFAULT_NORM), ::typeof(LinearAlgebra.opnorm), ::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), ::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), ::Nothing, ::Bool, ::Bool, ::Bool, ::Int64, ::Float64, ::Int64, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:default_set,),Tuple{Bool}}}, ::typeof(DiffEqBase.__init), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Any,1}) at /Users/abradley/.julia/packages/DelayDiffEq/nHoER/src/solve.jl:112
   [4] (::getfield(DiffEqBase, Symbol("#kw##__init")))(::NamedTuple{(:default_set,),Tuple{Bool}}, ::typeof(DiffEqBase.__init), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Any,1}) at ./none:0 (repeats 2 times)
   [5] #__solve#20(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:default_set,),Tuple{Bool}}}, ::typeof(DiffEqBase.__solve), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}) at /Users/abradley/.julia/packages/DelayDiffEq/nHoER/src/solve.jl:4
   [6] (::getfield(DiffEqBase, Symbol("#kw##__solve")))(::NamedTuple{(:default_set,),Tuple{Bool}}, ::typeof(DiffEqBase.__solve), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::MethodOfSteps{CompositeAlgorithm{Tuple{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType}},AutoSwitch{Tsit5,Rosenbrock23{0,false,DefaultLinSolve,DataType},Rational{Int64},Int64}},NLFunctional{Rational{Int64},Rational{Int64}},false}) at ./none:0
   [7] #__solve#2(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(DiffEqBase.__solve), ::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}, ::Nothing) at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/src/default_solve.jl:15
   [8] #solve#386 at ./none:0 [inlined]
   [9] solve(::DDEProblem{Float64,Tuple{Float64,Float64},Array{Float64,1},Tuple{},false,Nothing,DDEFunction{false,getfield(Main.##438, Symbol("##1#2")),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},getfield(Main.##438, Symbol("##3#4")),Nothing}) at /Users/abradley/.julia/packages/DiffEqBase/LCorD/src/solve.jl:27
   [10] top-level scope at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/test/default_dde_alg_test.jl:12
   [11] include at ./boot.jl:328 [inlined]
   [12] include_relative(::Module, ::String) at ./loading.jl:1094
   [13] include at ./Base.jl:31 [inlined]
   [14] include(::String) at /Users/abradley/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:23
   [15] top-level scope at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/test/runtests.jl:10
   [16] top-level scope at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [17] top-level scope at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/test/runtests.jl:10
   [18] eval(::Module, ::Any) at ./boot.jl:330
   [19] top-level scope at /Users/abradley/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:23
   [20] top-level scope at util.jl:156
   [21] include at ./boot.jl:328 [inlined]
   [22] include_relative(::Module, ::String) at ./loading.jl:1094
   [23] include(::Module, ::String) at ./Base.jl:31
   [24] include(::String) at ./client.jl:431
   [25] top-level scope at none:5
   [26] eval(::Module, ::Any) at ./boot.jl:330
   [27] exec_options(::Base.JLOptions) at ./client.jl:271
   [28] _start() at ./client.jl:464
  in expression starting at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/test/default_dde_alg_test.jl:12
  
Test Summary:         | Error  Total
Default DDE Algorithm |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/abradley/.julia/packages/DifferentialEquations/4jSpr/test/runtests.jl:10
ERROR: Package DifferentialEquations errored during testing
```

System:

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by AshtonSBradley** [comment] 2019-09-03 00:09
could this recent release have anything to do with it?
`  [276daf66] SpecialFunctions v0.8.0`

**Comment by AshtonSBradley** [comment] 2019-09-03 03:21
If I

 `pkg > pin SpecialFunctions@0.7.2` 

then tests pass.

**Comment by ChrisRackauckas** [comment] 2019-09-03 03:24
@kanav99 @YingboMa we need more tests on the auto-switch methods.

**Comment by ChrisRackauckas** [comment] 2019-09-03 10:53
Should be fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/917 . Turns out to be an ambiguity caused by a deprecation. A hotfix tag is coming through.

**Closed by ChrisRackauckas** 2019-09-03 10:53 UTC
