### ISSUE TITLE
Ability to repeat individual run from MC set.

### ISSUE THREAD

**Issue by tuckermcclure** [JuliaDiffEq/DifferentialEquations.jl#182] opened 2017-06-25 00:02 UTC
Frequently, a set of Monte-Carlo runs reveals an outlier, so it's useful to be able to recreate an individual run in order to debug and understand what happened. For stochastic systems, this involves getting the random number generator(s) back to the same state as at the start of that particular run. For non-stochastic, it simply implies storing the initial state itself. This type of functionality is crucial especially for more complex systems.

**Comment by ChrisRackauckas** [comment] 2017-06-25 00:36
I think there is an easy fix. There should just be a clear way to seed the rngs. I'll do this when I get back

**Comment by ChrisRackauckas** [comment] 2017-06-26 15:06
For non-stochastic, each solution type is returned by default. `sol.prob` holds the problem, and `sol.prob.u0` is then what you're looking for here.

For stochastic, controlling the RNG is needed. Currently it uses the global RNG, so the simple seeding idea I had won't work if there's also threading involved. This can be fixed by directly defining the `NoiseProcess` with different RNGs and seeds, but I think the stochastic problems should have a way to have a seed associated with them.

**Comment by ChrisRackauckas** [comment] 2017-06-26 19:20
It was actually a little difficult to find a setup which was sensible. This is what I came up with.

The `NoiseProcess` now allows you to give it an RNG. That has two advantages. For one, it's now not using the global RNG so it can be seeded in a thread-safe way. Secondly, it now uses RandomNumbers.jl, specifically the `Xoroshiro128Plus`, and tests show that RNG is both faster and more accurate (both my tests and the package author's). So now one has a lot more noise over the NoiseProcess if one uses `noise = ...`. The actual RNG is then stored as `prob.W.rng` which thus holds the seed as `prob.W.rng.seed` for standard RNGs.

But most people don't want to handle that level, so there is a higher level control. If the `noise` is not directly set, then the default noise process is seeded using the `seed`. `NoiseProblem`, `SDEProblem`, and `RODEProblem` all have a `seed` keyword argument which sets this seed. If the `seed` is not set, then the PROBLEM is not seeded, and so each time you solve you get a different solution (this is behavior that one would naturally expect. It breaks too many easy use-cases to just put a set random seed on the problem!). If the problem is seeded, then the same solution will come out every time.

So what this looks like is:

```julia
prob = SDEProblem(..., noise = WienerProcess(0.0,0.0,0.0,rng = MyRng()) # Can set RNG
prob = SDEProblem(...) # Standard stuff implies seed = 0 and different each time
prob = SDEProblem(...,seed = 10) # Sets the rng seed, every time it's solved is the same answer
```

Now, I can then add a `seed` on the `MonteCarloProblem`, but it seems unnecessary since there's already the `prob_func`. It's clear that if you want to seed the solutions, you should do something like:

```julia
prob_func = function (prob,i)
  SDEProblem(prob.f,prob.g,prob.u0,prob.tspan,seed=i)
end
```

Though I should probably make a `srand(prob,seed)` or something like that. `seed=0` means it's not set. I could also add an array of seeds for the `MonteCarloProblem` which would do essentially this, but that seems like overkill when the way to handle it explicitly is not much more difficult and is all pieces of the standard interface. Let me know if it would be requested though.

Anything I missed? Note this will be a mess to release so it may take a day or two to get it all out.

**Comment by ChrisRackauckas** [comment] 2017-06-26 19:58
SDEs and RODEs now save this seed in the solution. Not useful in the case where you set it, but very useful in the case where it's random.

**Comment by ChrisRackauckas** [comment] 2017-06-28 14:15
Complete and released.

**Closed by ChrisRackauckas** 2017-06-28 14:15 UTC

**Comment by tuckermcclure** [comment] 2017-06-28 15:51
This sounds like a good implementation. It seems to converge with designs I've seen for big simulation packages while still being small and easy to handle.
