### ISSUE TITLE
2nd order ODE solver no longer works if the solver is not specifed

### ISSUE THREAD

**Issue by alea54** [JuliaDiffEq/DifferentialEquations.jl#523] opened 2019-11-06 06:27 UTC
`
vl=(-10.0,2.0) ; equ_airy(v,x,p,t)=x*t
p_airy_1_0=SecondOrderODEProblem(equ_airy,1.0,0.0,vl) ;
f=solve(p_airy_1_0,reltol=1e-8,abstol=1e-8)
`
fails with error:
ERROR: type DynamicalODEFunction has no field jac_prototype
`
f=solve(p_airy_1_0,Vern7(),reltol=1e-8,abstol=1e-8)
`
works

**Comment by mmiller-max** [comment] 2020-01-14 02:18
I'm running into the same issue. If I don't specify the algorithm, solve defaults to a composite algorithm of Vern7 and Rodas4. Specifying the algorithm just as Rodas4 generates the same error as above.

None of the Rosenbrock Methods work - I'm guessing they are not compatible with the SecondOrderODEProblem (docs talk about them requiring a certain form) so the fix may be to stop Rosenbrock Methods being used as the default algorithm for second order ODEs?

I couldn't reproduce the error with the code above, so here is another example:
```
f!(ddu,du,u,p,t) = ddu = -u
prob = SecondOrderODEProblem{true}(f!,0.,0.,(0.,1.))
sol = solve(prob) # ERROR: type DynamicalODEFunction has no field jac_prototype
sol = solve(prob, Rodas4()) # ERROR: type DynamicalODEFunction has no field jac_prototype
sol = solve(prob, Vern7()) # Works fine
```

Interesting the same test using the not in place form generates a different error but only when Rodas4 is specified. If left to default, it works fine.
```
f(du,u,p,t) = -u
prob = SecondOrderODEProblem{false}(f,[0.],[0.],(0.,1.))
sol = solve(prob) # Works fine
sol = solve(prob, Rodas4()) # DimensionMismatch("parent has two elements, which is incompatible with size (2,2)"
sol = solve(prob, Vern7()) # Works fine
```

**Comment by ChrisRackauckas** [comment] 2020-01-19 21:46
Yup, I should set the default solver to something better for ODEs when a second order ODE is encountered.

**Comment by ChrisRackauckas** [comment] 2020-02-12 06:58
Fixed by https://github.com/JuliaDiffEq/DifferentialEquations.jl/pull/567

**Closed by ChrisRackauckas** 2020-02-12 06:58 UTC
