### ISSUE TITLE
DifferentialEquations fail during precompile

### ISSUE THREAD

**Issue by gaeblerh** [JuliaDiffEq/DifferentialEquations.jl#539] opened 2019-12-05 23:06 UTC
Hello,

I am new to Julia and I am trying to use the package DifferentialEquations. I have read about the issues during precompile, but I am unable to resolve the issue and am looking for some help. I have downladed v1.3 of Julia and am running it via Atom on windows 8. 

When I try using DifferentialEquations this is the error I get
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
ERROR: LoadError: EOFError: read end of file
Stacktrace:
 [1] read(::IOStream, ::Type{Int64}) at .\iostream.jl:361
 [2] parse_cache_header(::IOStream) at .\loading.jl:1334
 [3] stale_cachefile(::String, ::String) at .\loading.jl:1413
 [4] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:752
 [5] _require(::Base.PkgId) at .\loading.jl:1001
 [6] require(::Base.PkgId) at .\loading.jl:922
 [7] require(::Module, ::Symbol) at .\loading.jl:917
 [8] include at .\boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1105
 [10] include(::Module, ::String) at .\Base.jl:31
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:330 [inlined]
 [13] eval(::Expr) at .\client.jl:425
 [14] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SpecialFunctions\O3MVw\src\SpecialFunctions.jl:3
ERROR: LoadError: Failed to precompile SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] to C:\Users\user\.julia\compiled\v1.3\SpecialFunctions\78gOt_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\ForwardDiff\DVizx\src\ForwardDiff.jl:9
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to C:\Users\user\.julia\compiled\v1.3\ForwardDiff\k0ETY_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLSolversBase\NsXIC\src\NLSolversBase.jl:5
ERROR: LoadError: Failed to precompile NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] to C:\Users\user\.julia\compiled\v1.3\NLSolversBase\NEDD6_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLsolve\W6Ptc\src\NLsolve.jl:6
ERROR: LoadError: Failed to precompile NLsolve [2774e3e8-f4cf-5e23-947b-6d7e65073b56] to C:\Users\user\.julia\compiled\v1.3\NLsolve\KFCNP_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SteadyStateDiffEq\q0UMK\src\SteadyStateDiffEq.jl:6
ERROR: LoadError: Failed to precompile SteadyStateDiffEq [9672c7b4-1e72-59bd-8a11-6ac3964bc41f] to C:\Users\user\.julia\compiled\v1.3\SteadyStateDiffEq\lsCSw_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\DifferentialEquations\guw3o\src\DifferentialEquations.jl:9
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to C:\Users\user\.julia\compiled\v1.3\DifferentialEquations\UQdwS_15hil.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [2] _require(::Base.PkgId) at .\loading.jl:1024
 [3] require(::Base.PkgId) at .\loading.jl:922
 [4] require(::Module, ::Symbol) at .\loading.jl:917

Any help would be appreciated.

**Comment by ChrisRackauckas** [comment] 2019-12-06 01:35
Try `]build SpecialFunctions`. It looks like the binary didn't download.

**Comment by gaeblerh** [comment] 2019-12-06 01:40
I tried this, but it still failed. here is the new message

[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
ERROR: LoadError: EOFError: read end of file
Stacktrace:
 [1] read(::IOStream, ::Type{Int64}) at .\iostream.jl:361
 [2] parse_cache_header(::IOStream) at .\loading.jl:1334
 [3] stale_cachefile(::String, ::String) at .\loading.jl:1413
 [4] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:752
 [5] _require(::Base.PkgId) at .\loading.jl:1001
 [6] require(::Base.PkgId) at .\loading.jl:922
 [7] require(::Module, ::Symbol) at .\loading.jl:917
 [8] include at .\boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1105
 [10] include(::Module, ::String) at .\Base.jl:31
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:330 [inlined]
 [13] eval(::Expr) at .\client.jl:425
 [14] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SpecialFunctions\O3MVw\src\SpecialFunctions.jl:3
ERROR: LoadError: Failed to precompile SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] to C:\Users\user\.julia\compiled\v1.3\SpecialFunctions\78gOt_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\ForwardDiff\DVizx\src\ForwardDiff.jl:9
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to C:\Users\user\.julia\compiled\v1.3\ForwardDiff\k0ETY_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLSolversBase\NsXIC\src\NLSolversBase.jl:5
ERROR: LoadError: Failed to precompile NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] to C:\Users\user\.julia\compiled\v1.3\NLSolversBase\NEDD6_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLsolve\W6Ptc\src\NLsolve.jl:6
ERROR: LoadError: Failed to precompile NLsolve [2774e3e8-f4cf-5e23-947b-6d7e65073b56] to C:\Users\user\.julia\compiled\v1.3\NLsolve\KFCNP_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SteadyStateDiffEq\q0UMK\src\SteadyStateDiffEq.jl:6
ERROR: LoadError: Failed to precompile SteadyStateDiffEq [9672c7b4-1e72-59bd-8a11-6ac3964bc41f] to C:\Users\user\.julia\compiled\v1.3\SteadyStateDiffEq\lsCSw_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\DifferentialEquations\guw3o\src\DifferentialEquations.jl:9
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to C:\Users\user\.julia\compiled\v1.3\DifferentialEquations\UQdwS_15hil.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [2] _require(::Base.PkgId) at .\loading.jl:1024
 [3] require(::Base.PkgId) at .\loading.jl:922
 [4] require(::Module, ::Symbol) at .\loading.jl:917

**Comment by ChrisRackauckas** [comment] 2019-12-06 01:42
If you do `]add SpecialFunctions` then check `]st` what do you get?

**Comment by gaeblerh** [comment] 2019-12-06 01:43
(v1.3) pkg> add SpecialFunctions
  Updating registry at `C:\Users\user\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\user\.julia\environments\v1.3\Project.toml`
  [276daf66] + SpecialFunctions v0.9.0
  Updating `C:\Users\user\.julia\environments\v1.3\Manifest.toml`
 [no changes]

(v1.3) pkg> st
    Status `C:\Users\user\.julia\environments\v1.3\Project.toml`
  [c52e3926] Atom v0.11.3
  [0c46a032] DifferentialEquations v6.9.0
  [e5e0dc1b] Juno v0.7.2
  [5078a376] LazyArrays v0.14.10
  [1dea7af3] OrdinaryDiffEq v5.26.3
  [d96e819e] Parameters v0.12.0
  [276daf66] SpecialFunctions v0.9.0

**Comment by ChrisRackauckas** [comment] 2019-12-06 01:48
Looks like the new artifacts system is having issues since the root cause is 

https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/src/SpecialFunctions.jl#L3

and all of the packages are at their newest versions. `]add SpecialFunctions@0.8.0` would be a temporary fix, but let's pull someone in here who would know what's going on.

@ararslan @staticfloat

**Comment by gaeblerh** [comment] 2019-12-06 02:00
ive added the old version of SpecialFunctions and when I use DifferentialEquations I get stuck at the precompile message

[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]

**Comment by ChrisRackauckas** [comment] 2019-12-06 02:02
DifferentialEquations.jl is huge, so its precompile might take ~3-5 minutes IIRC. Sounds like it's working then. But that only happens when you update its component packages, so it's not an every time thing.

**Comment by gaeblerh** [comment] 2019-12-06 02:03
Awesome. I will let it compile and see what happens. Ill check back in a few days to see if there is a more permanent fix. Thanks for your help

**Comment by ararslan** [comment] 2019-12-06 03:07
Are you able to do `using SpecialFunctions` in the REPL?

**Comment by gaeblerh** [comment] 2019-12-06 13:16
Yes, both 0.8.0 and 0.9.0 work in the REPL

**Comment by ararslan** [comment] 2019-12-06 18:32
If SpecialFunctions 0.9 works in the REPL, that suggests to me that SpecialFunctions and/or OpenSpecFun_jll is not the culprit here. But I'm not really sure, because in the context of DifferentialEquations, it does seem to be the problem. :thinking:

**Comment by staticfloat** [comment] 2019-12-07 06:03
The fact that the error is in `parse_cache_header()` makes me think that it's a corrupted precompile image.  Try cleaning out all the `~/.julia/compiled/v1.3/SpecialFunctions/*.ji` files and try again.

**Comment by gaeblerh** [comment] 2019-12-07 16:36
I cleared out the files you suggested and re-ran DifferentialEquations. It still didn't work. This is the error I got

julia> using DifferentialEquations
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
ERROR: LoadError: EOFError: read end of file
Stacktrace:
 [1] read(::IOStream, ::Type{Int64}) at .\iostream.jl:361
 [2] parse_cache_header(::IOStream) at .\loading.jl:1334
 [3] stale_cachefile(::String, ::String) at .\loading.jl:1413
 [4] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:752
 [5] _require(::Base.PkgId) at .\loading.jl:1001
 [6] require(::Base.PkgId) at .\loading.jl:922
 [7] require(::Module, ::Symbol) at .\loading.jl:917
 [8] include at .\boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1105
 [10] include(::Module, ::String) at .\Base.jl:31
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:330 [inlined]
 [13] eval(::Expr) at .\client.jl:425
 [14] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SpecialFunctions\O3MVw\src\SpecialFunctions.jl:3
ERROR: LoadError: Failed to precompile SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] to C:\Users\user\.julia\compiled\v1.3\SpecialFunctions\78gOt_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\ForwardDiff\DVizx\src\ForwardDiff.jl:9
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to C:\Users\user\.julia\compiled\v1.3\ForwardDiff\k0ETY_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLSolversBase\NsXIC\src\NLSolversBase.jl:5
ERROR: LoadError: Failed to precompile NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] to C:\Users\user\.julia\compiled\v1.3\NLSolversBase\NEDD6_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\NLsolve\W6Ptc\src\NLsolve.jl:6
ERROR: LoadError: Failed to precompile NLsolve [2774e3e8-f4cf-5e23-947b-6d7e65073b56] to C:\Users\user\.julia\compiled\v1.3\NLsolve\KFCNP_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\SteadyStateDiffEq\q0UMK\src\SteadyStateDiffEq.jl:6
ERROR: LoadError: Failed to precompile SteadyStateDiffEq [9672c7b4-1e72-59bd-8a11-6ac3964bc41f] to C:\Users\user\.julia\compiled\v1.3\SteadyStateDiffEq\lsCSw_15hil.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\DifferentialEquations\guw3o\src\DifferentialEquations.jl:9
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to C:\Users\user\.julia\compiled\v1.3\DifferentialEquations\UQdwS_15hil.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [2] _require(::Base.PkgId) at .\loading.jl:1024
 [3] require(::Base.PkgId) at .\loading.jl:922
 [4] require(::Module, ::Symbol) at .\loading.jl:917

**Comment by staticfloat** [comment] 2019-12-11 20:43
Okay, the module that it's failing to load is one that `SpecialFunctions.jl` itself is trying to load, on line 3.  Try clearing out the `OpenSpecFun_jll` precompiled cache files in the same way.

**Comment by ChrisRackauckas** [comment] 2020-02-16 15:34
This has been fixed by artifacts.

**Closed by ChrisRackauckas** 2020-02-16 15:34 UTC
