### ISSUE TITLE
Precompilation fails (Version 1.0)

### ISSUE THREAD

**Issue by jackprob** [JuliaDiffEq/DifferentialEquations.jl#342] opened 2018-09-04 13:11 UTC
Hi I just installed your package, it looks great. When trying to execute the first beginner example [here](https://docs.juliadiffeq.org/latest/tutorials/ode_example.html), it starts to precompile and ends with this unfortunately:

```
ERROR: LoadError: LoadError: LoadError: UndefVarError: @pack not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/jprob/.julia/packages/OrdinaryDiffEq/c746g/src/OrdinaryDiffEq.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /home/jprob/.julia/packages/OrdinaryDiffEq/c746g/src/perform_step/exponential_rk_perform_step.jl:1434
in expression starting at /home/jprob/.julia/packages/OrdinaryDiffEq/c746g/src/perform_step/exponential_rk_perform_step.jl:1416
in expression starting at /home/jprob/.julia/packages/OrdinaryDiffEq/c746g/src/OrdinaryDiffEq.jl:98
ERROR: LoadError: Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to /home/jprob/.julia/compiled/v1.0/OrdinaryDiffEq/DlSvy.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jprob/.julia/packages/DiffEqCallbacks/dspKw/src/DiffEqCallbacks.jl:9
ERROR: LoadError: Failed to precompile DiffEqCallbacks [459566f4-90b8-5000-8ac3-15dfb0a30def] to /home/jprob/.julia/compiled/v1.0/DiffEqCallbacks/TKs5l.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jprob/.julia/packages/SteadyStateDiffEq/53QkP/src/SteadyStateDiffEq.jl:8
ERROR: LoadError: Failed to precompile SteadyStateDiffEq [9672c7b4-1e72-59bd-8a11-6ac3964bc41f] to /home/jprob/.julia/compiled/v1.0/SteadyStateDiffEq/lsCSw.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jprob/.julia/packages/DifferentialEquations/9VjqD/src/DifferentialEquations.jl:12
ERROR: LoadError: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to /home/jprob/.julia/compiled/v1.0/DifferentialEquations/UQdwS.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] include_string(::Module, ::String, ::String) at ./loading.jl:1002
 [10] (::getfield(Atom, Symbol("##120#125")){String,String,Module})() at /home/jprob/.julia/packages/Atom/Pab0Z/src/eval.jl:120
 [11] withpath(::getfield(Atom, Symbol("##120#125")){String,String,Module}, ::String) at /home/jprob/.julia/packages/CodeTools/8CjYJ/src/utils.jl:30
 [12] withpath at /home/jprob/.julia/packages/Atom/Pab0Z/src/eval.jl:46 [inlined]
 [13] #119 at /home/jprob/.julia/packages/Atom/Pab0Z/src/eval.jl:117 [inlined]
 [14] hideprompt(::getfield(Atom, Symbol("##119#124")){String,String,Module}) at /home/jprob/.julia/packages/Atom/Pab0Z/src/repl.jl:76
 [15] macro expansion at /home/jprob/.julia/packages/Atom/Pab0Z/src/eval.jl:116 [inlined]
 [16] (::getfield(Atom, Symbol("##118#123")){Dict{String,Any}})() at ./task.jl:85
```

**Comment by espintos** [comment] 2018-09-04 13:49
Exact same error.
Tried doing a pkg.update() and got the same error still.

This is on Windows 10 64 bit in my case.

**Comment by jackprob** [comment] 2018-09-04 13:52
I forgot to mention I am on Manjaro Linux

**Comment by devmotion** [comment] 2018-09-04 13:59
Hi! Sorry for the inconvenience, an update of Parameters.jl introduced a breaking change this morning. The issue is addressed in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/495.

As long as the fix is not released, you can pin Parameters to the previous version by executing `pin Parameters@0.9.2` in the Pkg-REPL (which you can reach by typing `]` in the Julia-REPL).

**Comment by zimmermm** [comment] 2018-09-04 14:12
Just as a remark: if I just use Pkg.add("DifferentialEquations"), Parameters.jl is not in the package list (]status) and I cannot pin it to 0.9.2. So one has to manually Pkg.add("Parameters") and then pin it to 0.9.2.

**Closed** 2018-09-05 15:03 UTC
