### ISSUE TITLE
Use an array of arrays as u prototype

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/DifferentialEquations.jl#572] opened 2020-03-04 20:51 UTC
Which is the most elegant way for solving a system of ODEs of the type:
```
da/dt = ...
db/dt = ...
dc/dt = ...
```
where a is `a` matrix of size `NxN`, `b` is a vector of size `N` and `c` is a scalar?

I believe that a good solution could be to set the `u` prototype using `u0` by:
```julia
u0 = Array{Array{Float64}}(undef, 3)
u0[1] = zeros(1)
u0[2] = zeros(N)
u0[3] = zeros(N, N)
```
but this does not work because
```julia
ERROR: TaskFailedException:
MethodError: no method matching zero(::Type{Array{Float64,1}})
```
So the only way of solving this type of problem is using a vector of dimension `N x N + N + 1`?

**Comment by ChrisRackauckas** [comment] 2020-03-04 22:10
Closing as a duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/254 . Arrays of arrays is really hard and its not something I'll promise soon.

**Closed by ChrisRackauckas** 2020-03-04 22:10 UTC

**Comment by rvignolo** [comment] 2020-03-04 22:17
Okay there is no problem at all! I will use a vector of that size, which is also a good approach. I just wanted to ask you if you have faced a case like the one described and which approach did you use.

As always, thanks Chris!

**Comment by ChrisRackauckas** [comment] 2020-03-04 22:19
Yup, for now use a vector, but do know this is something on my mind.
