### ISSUE TITLE
Unknown error with coupled foward backward ODE

### ISSUE THREAD

**Issue by mariepied** [JuliaDiffEq/DifferentialEquations.jl#294] opened 2018-05-23 14:56 UTC
I get an unknown error to report when solving three coupled equations the two first are backward, the last one is forward. We use the solution of one as parameter in the next one and try to find a fixed point so we iterate this systems of ODE several times. There is no stiffness and no callback. Some iteration can be performed before DiffEq crashes. 

Something went wrong. Integrator stepped past tstops but the algorithm was dtchangeable. Please report this error.

```julia
Stacktrace:
 [1] handle_tstop!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},Rational{Int64},Float64}},Array{Float64,1},Float64,Array{Any,1},Float64,Float64,Float64,Array{Array{Float64,1},1},OrdinaryDiffEq.ODECompositeSolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,Array{Any,1},#x_barj_func!,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},Rational{Int64},Float64}},OrdinaryDiffEq.CompositeInterpolationData{#x_barj_func!,Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}},OrdinaryDiffEq.Rosenbrock23Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,2},OrdinaryDiffEq.Rosenbrock23ConstantCache{Float64,Base.#identity,Base.#identity},DiffEqDiffTools.TimeGradientWrapper{#x_barj_func!,Array{Float64,1},Array{Any,1}},DiffEqDiffTools.UJacobianWrapper{#x_barj_func!,Float64,Array{Any,1}},DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}},DiffEqDiffTools.GradientCache{Void,Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},Rational{Int64},Float64}}}},#x_barj_func!,Void,OrdinaryDiffEq.CompositeCache{Tuple{OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}},OrdinaryDiffEq.Rosenbrock23Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,2},OrdinaryDiffEq.Rosenbrock23ConstantCache{Float64,Base.#identity,Base.#identity},DiffEqDiffTools.TimeGradientWrapper{#x_barj_func!,Array{Float64,1},Array{Any,1}},DiffEqDiffTools.UJacobianWrapper{#x_barj_func!,Float64,Array{Any,1}},DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DiffEqDiffTools.JacobianCache{Array{Float64,1},Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}},DiffEqDiffTools.GradientCache{Void,Array{Float64,1},Array{Float64,1},Val{:central},Float64,Val{true}}}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!},DataType},Rational{Int64},Float64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Void,Void,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1}}) at /home/piedmari/.julia/v0.6/OrdinaryDiffEq/src/integrators/integrator_utils.jl:402
```

**Comment by ChrisRackauckas** [comment] 2018-05-23 17:40
Thanks for the example. This was caused by changes in some parameters when the algorithms switch for stiffness switching (@YingboMa ). It was fixed by switching the algorithm and parameters prior to doing the `dt` celing operation. A new version of OrdinaryDiffEq.jl will be released shortly with this update. When this is merged you can `Pkg.update()` and you'll have the fix:

https://github.com/JuliaLang/METADATA.jl/pull/14809

**Closed by ChrisRackauckas** 2018-05-23 17:40 UTC

**Comment by ChrisRackauckas** [comment] 2018-05-24 07:08
Released.
