### ISSUE TITLE
"Dual" TypeError 

### ISSUE THREAD

**Issue by jebej** [JuliaDiffEq/DifferentialEquations.jl#164] opened 2017-05-09 22:30 UTC
I got a type error when trying Rosenbrock with a complex vector:
```
TypeError: Dual: in T, expected T<:Real, got Type{Complex{Float64}}

 in alg_cache(::OrdinaryDiffEq.Rosenbrock23{0,true,DiffEqBase.LinSolveFactorize{Base.LinAlg.#lufact!}}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Type{T}, ::Type{T}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Function, ::Float64, ::Type{Val{true}}) at C:\Users\Jeremy\.julia\v0.5\OrdinaryDiffEq\src\caches.jl:996
```

**Comment by ChrisRackauckas** [comment] 2017-05-09 22:32
Duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/110

**Closed by ChrisRackauckas** 2017-05-09 22:32 UTC
