### ISSUE TITLE
Updating quasi-static solutions in time

### ISSUE THREAD

**Issue by axelalmet** [JuliaDiffEq/DifferentialEquations.jl#528] opened 2019-11-20 20:20 UTC
Hi all,

I'm currently in the process of converting some problems from my thesis into a Julia implementation. This may not be a `DifferentialEquations`-specific problem, but I am trying to solve a sequence of quasi-static ODEs that describe a (growing) elastic rod attached to an elastic foundation, where the foundation attachments remodel to the current rod shape via the ODE:

![image](https://user-images.githubusercontent.com/10396553/69273941-41e7c480-0bd1-11ea-9532-08bef02cddf2.png)
where 
![image](https://user-images.githubusercontent.com/10396553/69274210-ce928280-0bd1-11ea-9e4a-5c5e096c22bf.png) is the foundation shape and  ![image](https://user-images.githubusercontent.com/10396553/69273965-4dd38680-0bd1-11ea-86aa-074706412375.png) is the current rod shape and is obtained by solving a `BVProblem` using `Shooting(Vern7())`. 

I find that when initialising the foundation shape using anonymous functions, e.g.
```
px = S -> S
py = S -> 0.0
```
everything solves fine (and quickly!). However, when I try and update the foundation shape via Forward Euler (bad, I know, but I will implement Implicit Trapezoid/Backward Euler once I get this working) and use the following code:

```
# Previous solution components
xOld  = S -> solOld(S, idx=2)
yOld = S -> solOld(2, idx=3)
pxOld = S -> px(S)
pyOld = S -> py(S)

# New solution components
xNew = S -> sol(S, idx=2)
yNew = S -> sol(S, idx=3) 

px = S -> pxOld(S) + dt*rho*(xOld(S) - pxOld(S))
py = S -> pyOld(S) + dt*rho*(yOld(S) - pyOld(S))
```

I find that Julia crashes when I try to evaluate these new foundation solutions with the error, `Bus error: 10`.  I think the error is coming from  the recursive way that I'm defining these functions, which means I'm running into stackoverflow land pretty quickly.

I'm sure there's a better way to do what I'm trying to do. If anyone could offer any pointers, I'd really appreciate it. Thank you for your help!

Best wishes,
Axel.

**Comment by ChrisRackauckas** [comment] 2019-11-20 21:59
I need a reproducible example to see where the error is. Without that, I am not sure I can help you.

**Comment by axelalmet** [comment] 2019-11-20 22:48
Hi Chris,

I should have realised that, sorry! Below is the code that I've been trying to run:

```
using BoundaryValueDiffEq, OrdinaryDiffEq

# Define the parameters
dt = 0.05 # time step 
g = 1.0 # Growth rate
kf = 0.01 # ratio of rod stiffness to foundation stiffness
h = 15.0 # cross-section height
w = 10.0  # cross-section width
L0 = 125.0 # dimensional length

# Define the foundation parameters
K = 12.0*kf*L0^4/(w*h^3)
rho = 10.0 # relaxation rate of foundation

# Rod stiffness (homogeneous for now)
Eb = 1.0

# Define the initial growth
gamma = 1 + dt

# Define the initial foundation
px = S -> S
py = S -> 0.0

# Initial guess for linear elastic foundation
initValues = [0.0, 0.0, -0.3351, -98.07, 0.0, 0.0, 0.9871]
SSpan = (0.0, 0.5) # Solution span

function RodOdes!(du, u, p, S)
    # Define solution components
    s, x, y, nx, ny, theta, m = u

    # gamma = S -> gammaOld(S).*(1 + 0.5*dt*W(sOld))./(1 - 0.5*dt*W(s))
    du[1] = gamma # s' = gamma
    du[2] = gamma.*cos(theta) # x' = gamma * cos(theta)
    du[3] = gamma.*sin(theta) # y' = gamma * sin(theta)
    du[4] = K.*gamma.*(x - px(S)) # nx' = k*gamma*(x - px)
    du[5] = K.*gamma.*(y - py(S)) # ny' = k*gamma*(y - py)
    du[6] = gamma.*m./Eb # theta' = gamma/Eb*m
    du[7] = gamma.*(nx.*sin(theta) - ny.*cos(theta)) # m' = gamma(nx*sin(theta) - ny*cos(theta))
end

function Bcs!(residual, u, p, S)

    residual[1] = u(0)[1] # s(0) = 0
    residual[2] = u(0)[2] # x(0) = 0
    residual[3] = u(0)[5] # ny(0) = 0
    residual[4] = u(0)[6] # theta(0) = 0
    residual[5] = u(0.5)[2] - 0.5 # x(L) = L/2
    residual[6] = u(0.5)[3] # y(L) = 0
    residual[7] = u(0.5)[6] # theta(L) = 0

end

# Obtain the intial solution
bvp = BVProblem(RodOdes!, Bcs!, initValues, SSpan)
@time sol = solve(bvp, Shooting(Vern7()))

# Update the foundation. We need the solutions for x and y to do this.
xOld = S -> sol(S, idx=2)
yOld = S -> sol(S, idx=3) 
pxOld = S -> px(S)
pyOld = S -> py(S)

px = S -> pxOld(S) + dt*rho*(xOld(S) - pxOld(S))
py = S ->  pyOld(S) + dt*rho*(yOld(S)  pyOld(S))


# Update the solutions and current arc length
solOld = sol

# Now try to solve it again
initValues = solOld(0)
bvpNew = BVProblem(RodOdes!, Bcs!, initValues, SSpan)
solNew = solve(bvp, Shooting(Vern7()))
```

Note that the above time stepping for the foundation wouldn't actually be the case after the initial solution, but it's illustrative of the problem I have.

Hope this is more useful.

**Comment by ChrisRackauckas** [comment] 2019-11-20 23:19
You made an infinite recursion. px calls pxOld which calls px which call pxOld which ... I wouldn't overwrite your globals to the same name.

**Comment by axelalmet** [comment] 2019-11-21 09:02
Hi Chris,

Thanks for the answer, I suspected as much! Is there a best practice, so to speak, to avoid this, by say using local variables or `let`? Sorry if this is a dumb question, I'm admittedly still learning the ropes of Julia.

**Comment by ChrisRackauckas** [comment] 2019-11-21 14:00
Just name it differently if it's global, or use local variables? Loop scopes are already local so you wouldn't have the problem with things like loops. It's just that you specifically chose two globals to have the same name.

I'll close this since there's no DifferentialEquations.jl issue here, but feel free to keep chatting. You may want to join the Julia Slack for more discussion: https://slackinvite.julialang.org/

**Closed by ChrisRackauckas** 2019-11-21 14:00 UTC
