### ISSUE TITLE
Unsatisfiable requirements detected when adding DifferentialEquations package to JuliaPro 0.6.4.1

### ISSUE THREAD

**Issue by noisyoscillator** [JuliaDiffEq/DifferentialEquations.jl#349] opened 2018-09-12 09:06 UTC
I am trying out Julia after hearing good things about it from a talk by David Sanders at our Institute. Installed JuliaPro 0.6.4.1 on Windows 10 64 bit PC. Encountered the following error while adding DifferentialEquations package.

```
julia> Pkg.add("DifferentialEquations")
ERROR: Unsatisfiable requirements detected for package NLSolversBase:
├─version range [6.1.1,6.1.1+) set by an explicit requirement
├─version range [5.0.0,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2+)
:
│ ├─version range [0.15.2,0.15.2+) set by an explicit requirement
│ ├─version range [0.0.0-,∞) required by package QuantEcon, whose allowed version range is [0.14.2,0
.14.2+):
│ │ └─version range [0.14.2,0.14.2+) set by an explicit requirement
│ └─version range [0.0.0-,∞) required by package KernelDensity, whose allowed version range is [0.4.
1,0.4.1+):
  │ ├─version range [0.4.1,0.4.1+) set by an explicit requirement
  │ └─version range [0.0.0-,∞) required by package Gadfly, whose allowed version range is [0.7.0,0.7
.0+):
    │ └─version range [0.7.0,0.7.0+) set by an explicit requirement
├─version range [5.0.0,∞) required by package LineSearches, whose allowed version range is [6.0.2,6.
0.2+):
│ ├─version range [6.0.2,6.0.2+) set by an explicit requirement
│ ├─version range [6.0.1,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2
+):
│ │ └─[see above for Optim backtrace]
│ └─version range [0.0.1,1.0.0-) or [1.0.0,∞) required by package NLsolve, whose allowed version ran
ge is [0.7.3,∞):
  │ └─version range [0.7.3,∞) required by package OrdinaryDiffEq, whose allowed version range is [0.
0.0,∞):
    │ └─version range [0.0.0,∞) required by package DifferentialEquations, whose allowed version ran
ge is [0.0.0-,∞):
      │ └─version range [0.0.0-,∞) set by an explicit requirement
└─version range [0.0.1,5.0.0) required by package NLsolve, whose allowed version range is [0.7.3,∞):

  └─[see above for NLsolve backtrace]
The intersection of the requirements is empty.
filter_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.
Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:341

prune_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.T
ypes.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:370
prune_dependencies(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.P
kg.Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:
584
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{Str
ing,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:500
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\e
ntry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where
N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
```

**Comment by ChrisRackauckas** [comment] 2018-09-13 17:05
Duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/265#issuecomment-421079843

**Closed by ChrisRackauckas** 2018-09-13 17:05 UTC
