### ISSUE TITLE
ProgressMeter

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/DifferentialEquations.jl#304] opened 2018-06-08 14:49 UTC
Hi,

This is more a question than an issue... Should I post this on Discourse?

My question is, can we monitor progress in console using ProgressMeter?

Tahnk you for your help and sorry for the 'spam'

Bests

**Comment by ChrisRackauckas** [comment] 2018-06-08 14:51
Duplicate of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/121 which is then discussed here: https://github.com/JunoLab/Juno.jl/issues/29 . The general solution requires the new v0.7 logging system and so it'll be one of the first changes we make in v0.7 since it'll be pretty simple to do.

**Closed by ChrisRackauckas** 2018-06-08 14:51 UTC

**Comment by rveltz** [comment] 2018-06-08 14:56
thank you for the prompt answer and congrats for your defense, I watched it.

**Comment by ChrisRackauckas** [comment] 2018-06-08 14:58
Thanks!
